
const ALPHABET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
const USERNAME_PATTERN = '^[a-zA-Z0-9]+$';
const PASSWORD_PATTERN = '^[a-zA-Z]+[0-9]*[._!]+';
const MAX_USERNAME_LENGTH = 20;
const MIN_USERNAME_LENGTH = 3;
const MAX_PASSWORD_LENGTH = 20;
const MIN_PASSWORD_LENGTH = 6;

export default {
    ALPHABET,
    MAX_USERNAME_LENGTH,
    MIN_USERNAME_LENGTH,
    MAX_PASSWORD_LENGTH,
    MIN_PASSWORD_LENGTH,
    USERNAME_PATTERN,
    PASSWORD_PATTERN
};

